remote_theme: jekyll/minima
title: Tommaso's
description: This is just one of my creative outlets, I'll just have some fun writing random stuff.
minima:
  skin: dark
author:
  name: Tommaso De Tommaso
  email: "thisistommaso@gmail.com"
